#!/bin/sh
export QT_QPA_PLATFORMTHEME=kde
export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORM=wayland;xcb
export XDG_CURRENT_DESKTOP=sway

export WLR_NO_HARDWARE_CURSORS=1
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

exec sway --unsupported-gpu
