#################################
#            Options            #
#################################

font pango:Source Code Pro Semi-Bold 8

#~~~ blur
blur enable
blur_radius 10
blur_passes 3
blur_noise 0.02
blur_saturation 1.2
blur_contrast 1.1
shadows disable
corner_radius 12

#~~~ gaps
gaps inner                                       5
gaps outer                                       4
smart_gaps on
smart_borders on
default_border                                   pixel 2
default_floating_border                          none
floating_modifier                                $mod
hide_edge_borders --i3                           none
workspace_layout default

seat seat0 xcursor_theme                         breeze_cursors 32

#~~~ sway
bar {
	swaybar_command                              "waybar"
	workspace_buttons                            yes
}

