exec pipewire
#exec wireplumber
exec /usr/libexec/polkit-kde-authentication-agent-1
exec swaybg -i ~/.config/sway/wallpapers/alcoholic.jpg
exec swayosd-server 
exec swaync 
exec autotiling-rs 

#exec blueman-applet
